CREATE TABLE MEMBER (
  MEMBER_ID BIGSERIAL NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  PASSWORD TEXT NOT NULL,
  CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  WEB_SITE_ID INT NOT NULL,
  CONSTRAINT MEMBER_PKEY PRIMARY KEY(MEMBER_ID)
);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE UNIQUE INDEX MEMBER__EMAIL__WEB_SITE_ID_KEY ON MEMBER
  USING btree (EMAIL, WEB_SITE_ID);

CREATE UNIQUE INDEX MEMBER__USER_NAME__WEB_SITE_ID_KEY ON MEMBER
  USING btree (USER_NAME, WEB_SITE_ID);
