CREATE TABLE WEB_SITE (
	WEB_SITE_ID BIGSERIAL NOT NULL,
	DOMAIN_NAME VARCHAR(255) NOT NULL,
	SET_UP_COMPLETE BOOLEAN NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT WEB_SITE_PKEY PRIMARY KEY(WEB_SITE_ID)
);

CREATE UNIQUE INDEX WEB_SITE__DOMAIN_NAME_KEY ON WEB_SITE
	USING btree (DOMAIN_NAME);

CREATE TABLE WEB_PAGE_TEMPLATE (
	WEB_PAGE_TEMPLATE_ID BIGSERIAL NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	NAME_EDITS VARCHAR(100) NOT NULL,
	CONTENT_EDITS TEXT NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	CONSTRAINT WEB_PAGE_TEMPLATE_PKEY PRIMARY KEY(WEB_PAGE_TEMPLATE_ID)
);

ALTER TABLE WEB_PAGE_TEMPLATE
ADD CONSTRAINT WEB_PAGE_TEMPLATE__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE TABLE WEB_PAGE_TEMPLATE_HISTORY (
	WEB_PAGE_TEMPLATE_HISTORY_ID BIGSERIAL NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_PAGE_TEMPLATE_ID INT NOT NULL,
	CONSTRAINT WEB_PAGE_TEMPLATE_HISTORY_PKEY PRIMARY KEY(WEB_PAGE_TEMPLATE_HISTORY_ID)
);

ALTER TABLE WEB_PAGE_TEMPLATE_HISTORY
ADD CONSTRAINT WEB_PAGE_TEMPLATE_HISTORY__WEB_PAGE_TEMPLATE_FK FOREIGN KEY (WEB_PAGE_TEMPLATE_ID)
REFERENCES WEB_PAGE_TEMPLATE(WEB_PAGE_TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE TABLE WEB_PAGE (
	WEB_PAGE_ID BIGSERIAL NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	PATH VARCHAR(1000),
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(4000) NOT NULL,
	CONTENT TEXT NOT NULL,
	PARAMETERS TEXT NOT NULL,
	TYPE_EDITS VARCHAR(50) NOT NULL,
	PATH_EDITS VARCHAR(1000) NOT NULL,
	TITLE_EDITS VARCHAR(255) NOT NULL,
	DESCRIPTION_EDITS VARCHAR(4000) NOT NULL,
	CONTENT_EDITS TEXT NOT NULL,
	PARAMETERS_EDITS TEXT NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	WEB_PAGE_TEMPLATE_ID INT NOT NULL,
	WEB_PAGE_TEMPLATE_ID_EDITS INT NOT NULL,
	CONSTRAINT WEB_PAGE_PKEY PRIMARY KEY(WEB_PAGE_ID)
);

ALTER TABLE WEB_PAGE
ADD CONSTRAINT WEB_PAGE__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE WEB_PAGE
ADD CONSTRAINT WEB_PAGE__WEB_PAGE_TEMPLATE_FK FOREIGN KEY (WEB_PAGE_TEMPLATE_ID)
REFERENCES WEB_PAGE_TEMPLATE(WEB_PAGE_TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE WEB_PAGE
ADD CONSTRAINT WEB_PAGE__WEB_PAGE_TEMPLATE_EDITS_FK FOREIGN KEY (WEB_PAGE_TEMPLATE_ID_EDITS)
REFERENCES WEB_PAGE_TEMPLATE(WEB_PAGE_TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE UNIQUE INDEX WEB_PAGE__PATH__WEB_SITE_ID_KEY ON WEB_PAGE
	USING btree (PATH, WEB_SITE_ID);

CREATE TABLE WEB_PAGE_HISTORY (
	WEB_PAGE_HISTORY_ID BIGSERIAL NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	PATH VARCHAR(1000) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(4000) NOT NULL,
	CONTENT TEXT NOT NULL,
	PARAMETERS TEXT NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_PAGE_TEMPLATE_ID INT NOT NULL,
	WEB_PAGE_ID INT NOT NULL,
	CONSTRAINT WEB_PAGE_HISTORY_PKEY PRIMARY KEY(WEB_PAGE_HISTORY_ID)
);

ALTER TABLE WEB_PAGE_HISTORY
ADD CONSTRAINT WEB_PAGE_HISTORY__WEB_PAGE_TEMPLATE_FK FOREIGN KEY (WEB_PAGE_TEMPLATE_ID)
REFERENCES WEB_PAGE_TEMPLATE(WEB_PAGE_TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE WEB_PAGE_HISTORY
ADD CONSTRAINT WEB_PAGE_HISTORY__WEB_PAGE_FK FOREIGN KEY (WEB_PAGE_ID)
REFERENCES WEB_PAGE(WEB_PAGE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE TABLE MEDIA (
	MEDIA_ID BIGSERIAL NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	PATH VARCHAR(1000) NOT NULL,
	CONTENT BYTEA NOT NULL,
	TYPE_EDITS VARCHAR(50) NOT NULL,
	PATH_EDITS VARCHAR(1000) NOT NULL,
	CONTENT_EDITS BYTEA NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	CONSTRAINT MEDIA_PKEY PRIMARY KEY(MEDIA_ID)
);

ALTER TABLE MEDIA
ADD CONSTRAINT MEDIA__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE UNIQUE INDEX MEDIA__PATH__WEB_SITE_ID_KEY ON MEDIA
	USING btree (PATH, WEB_SITE_ID);

CREATE TABLE MEDIA_HISTORY (
	MEDIA_HISTORY_ID BIGSERIAL NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	PATH VARCHAR(1000) NOT NULL,
	CONTENT BYTEA NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	PUBLISH_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	CONSTRAINT MEDIA_HISTORY_PKEY PRIMARY KEY(MEDIA_HISTORY_ID)
);

ALTER TABLE MEDIA_HISTORY
ADD CONSTRAINT MEDIA_HISTORY__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE TABLE ADMIN_USER (
	ADMIN_USER_ID BIGSERIAL NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	PASSWORD TEXT NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	CONSTRAINT ADMIN_USER_PKEY PRIMARY KEY(ADMIN_USER_ID)
);

ALTER TABLE ADMIN_USER
ADD CONSTRAINT ADMIN_USER__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE UNIQUE INDEX ADMIN_USER__EMAIL__WEB_SITE_ID_KEY ON ADMIN_USER
	USING btree (EMAIL, WEB_SITE_ID);

CREATE UNIQUE INDEX ADMIN_USER__USER_NAME__WEB_SITE_ID_KEY ON ADMIN_USER
	USING btree (USER_NAME, WEB_SITE_ID);

CREATE TABLE WEB_PAGE_SEARCH_PARAM (
	WEB_PAGE_SEARCH_PARAM_ID BIGSERIAL NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	VALUE VARCHAR(255) NOT NULL,
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_PAGE_ID INT NOT NULL,
	CONSTRAINT WEB_PAGE_SEARCH_PARAM_PKEY PRIMARY KEY(WEB_PAGE_SEARCH_PARAM_ID)
);

ALTER TABLE WEB_PAGE_SEARCH_PARAM
ADD CONSTRAINT WEB_PAGE_SEARCH_PARAM__WEB_PAGE_FK FOREIGN KEY (WEB_PAGE_ID)
REFERENCES WEB_PAGE(WEB_PAGE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;
