CREATE TABLE REDIRECT (
	WEB_PAGE_ID BIGSERIAL NOT NULL,
	FROM_PATH VARCHAR(1000),
	TO_PATH VARCHAR(1000),
	CREATE_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	MODIFY_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	WEB_SITE_ID INT NOT NULL,
	CONSTRAINT REDIRECT_PKEY PRIMARY KEY(WEB_PAGE_ID)
);

ALTER TABLE REDIRECT
ADD CONSTRAINT REDIRECT__WEB_SITE_FK FOREIGN KEY (WEB_SITE_ID)
REFERENCES WEB_SITE(WEB_SITE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE UNIQUE INDEX REDIRECT__FROM_PATH__WEB_SITE_ID_KEY ON REDIRECT
	USING btree (FROM_PATH, WEB_SITE_ID);
