ALTER TABLE WEB_PAGE_HISTORY
ALTER COLUMN WEB_SITE_ID SET NOT NULL;

-- Drop the constraints so we will be able to delete from WEB_PAGE_TEMPLATE
ALTER TABLE WEB_PAGE_TEMPLATE_HISTORY
DROP CONSTRAINT WEB_PAGE_TEMPLATE_HISTORY__WEB_PAGE_TEMPLATE_FK;

-- Drop the constraints so we will be able to delete from WEB_PAGE
ALTER TABLE WEB_PAGE_HISTORY
DROP CONSTRAINT WEB_PAGE_HISTORY__WEB_PAGE_FK;
